name: Publish [Github]
on: 
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        node: ["lts/*"]
    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4
      - name:  Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: next-9
          standalone: true
      - name:  Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
          cache: "pnpm"
      - name:  Install dependencies
        run: pnpm install
      - name: Ô∏è Build Package
        run: pnpm build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.ROBOT_TOKEN }}
          registry: "https://npm.pkg.github.com"
      - name:  Add comment to release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ROBOT_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: 'PraxiveSoftware',
              repo: 'Samurai',
              body: 'This release corresponds to the commit SHA: ${{ github.sha }}'
            })
